title: 巴黎街区地图
description: 巴黎风险区地图

url: https://paris-risk-zones.github.io

# Locally
baseurl: ""
#remote_theme: piazzai/jekyll-nagymaros

# Online
#baseurl: ""
#theme: jekyll-nagymaros

include:
  - assets


copyright: Place Holder
indexing: true

permalink: pretty

exclude:
  - LICENSE
  - README.md
  - run.sh

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
